FROM ghcr.io/openclaw/openclaw:main

USER root

# Install runtime entrypoint: writes config with injected token, calls original node entrypoint
# Binary is: node openclaw.mjs gateway (NOT "openclaw" binary)
RUN echo "IyEvYmluL3NoCnNldCAtZQpUT0tFTj0iJHtPUEVOQ0xBV19HQVRFV0FZX1RPS0VOOi1ub3JtaWVjbGF3fSIKQ09ORklHPSJ7XCJnYXRld2F5XCI6e1wiYmluZFwiOlwibGFuXCIsXCJwb3J0XCI6ODA4MCxcImNvbnRyb2xVaVwiOntcImVuYWJsZWRcIjp0cnVlLFwiYWxsb3dJbnNlY3VyZUF1dGhcIjp0cnVlfSxcImF1dGhcIjp7XCJtb2RlXCI6XCJ0b2tlblwiLFwidG9rZW5cIjpcIiVzXCJ9fX0iCm1rZGlyIC1wIC9yb290Ly5vcGVuY2xhdyAvaG9tZS9ub2RlLy5vcGVuY2xhdwpwcmludGYgIiRDT05GSUdcbiIgIiRUT0tFTiIgPiAvcm9vdC8ub3BlbmNsYXcvb3BlbmNsYXcuanNvbgpwcmludGYgIiRDT05GSUdcbiIgIiRUT0tFTiIgPiAvaG9tZS9ub2RlLy5vcGVuY2xhdy9vcGVuY2xhdy5qc29uCmVjaG8gIltub3JtaWVjbGF3XSBDb25maWcgd3JpdHRlbi4gVG9rZW46ICRUT0tFTiIKY2QgL2FwcApleGVjIGRvY2tlci1lbnRyeXBvaW50LnNoIG5vZGUgb3BlbmNsYXcubWpzIGdhdGV3YXkgLS1hbGxvdy11bmNvbmZpZ3VyZWQK" | base64 -d > /usr/local/bin/normieclaw-start && \
    chmod +x /usr/local/bin/normieclaw-start

ENTRYPOINT ["/usr/local/bin/normieclaw-start"]
